### ISSUE TITLE
功能建议：卡池导入相关

### ISSUE THREAD

**Issue by DentistCode** [Makstein/SnowbreakGachaExport#10]
> 二编：发现未到五星的抽卡记录不会显示

1. 功能建议1：显示保底次数（因为不显示的话，以为自己没有导入成功）
2. 功能建议2：增加手动数据备份功能，方便迁移（看见自动备份的功能啦HistoryCache.json_Backup）

版本：v2.0.0（刚下载的）

功能建议对应的截图：

![Snipaste_2024-07-03_16-21-33](https://github.com/Makstein/SnowbreakGachaExport/assets/86056063/9ad952be-6173-400f-9e35-243d15d56d72)
> 界面截图

**Comment by Makstein** [comment]
1. 这个我后边做100和50池子分池统计的时候可以加一下
2. 记录导入导出是好建议，应该会在下版本实现

**Comment by KirisameVanilla** [comment]
@DentistCode 目前已经全部实现了，等ci的自动发布配好就可以用新的了
