### ISSUE TITLE
去重问题

### ISSUE THREAD

**Issue by JinShichang** [Makstein/SnowbreakGachaExport#12]
![QQ20240713-220124](https://github.com/user-attachments/assets/b935122c-a59c-4695-9323-f540c397ce00)
如图 重复分析会重复记录

**Comment by Makstein** [comment]
可以上传下软件目录下Data/History.json文件吗？有可能是ID生成问题，有时间我会看一下

**Comment by JinShichang** [comment]
> 可以上传下软件目录下Data/History.json文件吗？有可能是ID生成问题，有时间我会看一下

抱歉 现在才看到
[Data.zip](https://github.com/user-attachments/files/16236837/Data.zip)

**Comment by KirisameVanilla** [comment]
编辑了 当我没说喵 我理解错误了
~我觉得是比较新historyString和旧historyString 的问题。我觉得这个问题是因为用户以前录入过的数据因为2个月的时间期限而无法查看，然后读入新的的时候，程序判定是不一样的记录，然后全部重新插入一次的原因。比如我现在有"Jan 1st"和"Feb 1st"两个抽卡记录，然后现在是Mar 2nd，因此网页可以查看的是"Feb 1st"和"Mar 2nd"。然后程序发现这两个string不相等，就将"Feb 1st"和"Mar 2nd"插入到"Jan 1st"和"Feb 1st"之后，最终得到了"Jan 1st""Feb 1st""Feb 1st"和"Mar 2nd"四个抽卡记录~

**Comment by KirisameVanilla** [comment]
我尝试了一下，似乎要插入错误也是插入到原本的记录前面？不知道为什么楼主的会插入到json末尾

**Comment by Makstein** [comment]
用手机看了看，重复数据插入在中间我目前没什么思路，最近几周，我的工作正在让我像陀螺一样旋转，近期可能没什么时间查找原因，后面有时间我再尝试复现一下

**Comment by KirisameVanilla** [comment]
我又看了一下作者您的代码，我认为您原本的merge逻辑是没问题的，我不明白为什么会出现这个issue里面的bug（把新的数据插入到结尾去了）

**Comment by KirisameVanilla** [comment]
@JinShichang 这位用户，您的里芙和凯茜娅是不是100池抽的，琴诺芬妮苔丝是不是80池抽的？也许问题是出在了80和100池混着记录

**Comment by JinShichang** [comment]
> @JinShichang 这位用户，您的里芙和凯茜娅是不是100池抽的，琴诺芬妮苔丝是不是80池抽的？也许问题是出在了80和100池混着记录

是的，100池出来之后就没再碰过米池

**Comment by KirisameVanilla** [comment]
这个的问题出在混用记录。在100池子记录第一次之后，在80池记录第二次，这时记录的HEAD是80池的，第三次又记录了100池，程序发现当前HEAD在100池的游戏内抽卡记录里无法找到，因此全部重新记录，进而导致了重复。解决方法是手动分离data/History.json，放入对应的池子记录内。然后使用新版本https://github.com/Makstein/SnowbreakGachaExport/releases/tag/v2.0.2 。BTW这个新版本界面上的【导入记录】实现的是全部覆盖
