### ISSUE TITLE
可否增加窗口化获取抽卡记录支持？

### ISSUE THREAD

**Issue by KirisameVanilla** [Makstein/SnowbreakGachaExport#15]
使用**1600:900窗口化**时获取抽卡记录会提示
游戏分辨率初始化失败：非16: 9分辨率

**Comment by KirisameVanilla** [comment]
以及后续会直接闪退
![image](https://github.com/user-attachments/assets/8cc4fc68-2266-48a4-a2cf-62370aac020e)

**Comment by KirisameVanilla** [comment]
闪退已在pull request #14 修复

**Comment by YuukyuuKikan** [comment]
我使用1600x900分辨率的无边框全屏也会触发该提示。

**Comment by KirisameVanilla** [comment]
> 我使用1600x900分辨率的无边框全屏也会触发该提示。

这个应该是奇妙bug 建议是切到游戏再切出来试一下

**Comment by Makstein** [comment]
应该已经在最新版中修复
