### ISSUE TITLE
读取记录之后把游戏进程转为了后台程序

### ISSUE THREAD

**Issue by dsy-lee** [Makstein/SnowbreakGachaExport#6]
<img width="764" alt="4e371e0780a5b2e56170231803af41ba" src="https://github.com/Makstein/SnowbreakGachaExport/assets/107312118/ea43e89f-52e0-4137-b3a1-38a136a3ce7c">
具体情况：点击获取记录，开始获取，获取结束之后尘白禁区游戏界面立刻消失转到了SnowbreakToolbox界面，我开始以为游戏闪退了，重新启动游戏发现提示游戏运行中，在任务管理器发现游戏从应用转到了后台进程。此时似乎只能在任务管理器中结束游戏进程才能重新进行游戏。

**Comment by Makstein** [comment]
这个问题应该是我在统计结束后，错误的将游戏窗口模式设置为了HIDE，下个版本会修复

**Comment by dsy-lee** [comment]
感谢大佬

**Comment by Makstein** [comment]
在v2.0.0-alpha2中已修复
