### ISSUE TITLE
1.X的抽卡记录能迁移到2.X吗？

### ISSUE THREAD

**Issue by TheTychoStar** [Makstein/SnowbreakGachaExport#8]
直接把Data里面的json复制过去可以识别，但是不会自动过滤1.X的记录，获取的时候不会剔除重复的部分，看了下json格式也不太一样，手动改好像有点不太现实。

**Comment by Makstein** [comment]
你能上传一下你的记录json文件吗？

**Comment by TheTychoStar** [comment]
已上传。v1.1的记录是获取过两次的，第一次较早，第二次是今天获取的。v2.0的记录只包含了今天获取一次的记录。因为玩得时间不长，只有限定角色池和限定武器池超过了200抽。v1.1比v2.0在这两个池多了一小部分记录。
主要是时间格式不一样，type数值不太一样，以及1.1版本有部分文字识别错误，如图所示。
![comparison](https://github.com/Makstein/SnowbreakGachaExport/assets/75252778/85002b26-d3d4-46ec-a9cb-b3991be51cb9)
[HistoryCache_v1.1.json](https://github.com/Makstein/SnowbreakGachaExport/files/15411011/HistoryCache_v1.1.json)
[HistoryCache_v2.0_a2.json](https://github.com/Makstein/SnowbreakGachaExport/files/15411012/HistoryCache_v2.0_a2.json)

**Comment by Makstein** [comment]
> 获取的时候不会剔除重复的部分
> 时间格式不一样

我忘记测试这个了，这个应该是因为我在2.0版本中没有处理识别后的名称和时间格式，导致ID格式与1.x版本中的不同，程序合并记录时通过这个ID来判断，所以也无法正确合并，我会在下版本修复

Type和名字识别错误的问题，是因为1.x版本使用的OCR模型对中文识别较差。已经识别的结果，程序无法反推出正确名称，如果你确实想保留这些记录，可以手动更改一下需要展示的五星角色或武器名称，Type 0代表角色 1代表武器，角色名称格式为 `角色名-后缀`

**Comment by TheTychoStar** [comment]
> > 获取的时候不会剔除重复的部分
> > 时间格式不一样
> 
> 我忘记测试这个了，这个应该是因为我在2.0版本中没有处理识别后的名称和时间格式，导致ID格式与1.x版本中的不同，程序合并记录时通过这个ID来判断，所以也无法正确合并，我会在下版本修复
> 
> Type和名字识别错误的问题，是因为1.x版本使用的OCR模型对中文识别较差。已经识别的结果，程序无法反推出正确名称，如果你确实想保留这些记录，可以手动更改一下需要展示的五星角色或武器名称，Type 0代表角色 1代表武器，角色名称格式为 `角色名-后缀`

明白了，识别错误这个我估计也是没法反推的了。好在少的记录不多，手动改一下五星吧。
